{
  "models": [
    {
      "title": "DeepSeek Coder",
      "provider": "ollama",
      "model": "deepseek-coder-v2"
    },
    {
      "title": "Qwen 7B",
      "provider": "ollama",
      "model": "qwen2.5:7b"
    }
  ],
  "tabAutocompleteModel": {
    "title": "DeepSeek Autocomplete",
    "provider": "ollama",
    "model": "deepseek-coder-v2"
  }
}